version: "3.4"

services:
  db:
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_DB=tasksbucket
      - POSTGRES_USER=challengetask
      - POSTGRES_PASSWORD=edc43A35

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - ./.develop.env
    depends_on:
      - db
